#! /bin/bash
LLAMA_PATH=/home/marc/local/llama.cpp/build-vulkan-radv/bin
export HF_HUB_CACHE=/home/lemonade/hub
export ROCBLAS_USE_HIPBLASLT=1
export GGML_CUDA_ENABLE_UNIFIED_MEMORY=ON
export LD_LIBRARY_PATH=$LLAMA_PATH:/usr/lib/llvm-18/lib:$LD_LIBRARY_PATH

# Forward termination signals to child process
cleanup() { kill 0 2>/dev/null; exit $?; }
trap cleanup SIGTERM SIGHUP SIGINT

echo 'vulkan-radv $LLAMA_PATH/llama-server "$@"'
$LLAMA_PATH/llama-server --threads $(nproc) "$@"
