FROM localhost/llama-strix-halo:vulkan

RUN printf '#!/bin/bash\nexport LLAMA_CACHE=/home/lemonade/hub\nexport ROCBLAS_USE_HIPBLASLT=1\nexport GGML_CUDA_ENABLE_UNIFIED_MEMORY=ON\nexec /usr/local/bin/llama-server -fa on -ngl 999 --no-mmap "$@"\n' > /usr/local/bin/llama-vulkan.sh && chmod 755 /usr/local/bin/llama-vulkan.sh
